UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : THANKS LET ME PULL THAT INFORMATION UP O K I SEE YOUR PACKAGE AS MARKED AS OUT FOR DELIVERY TO DAY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOME
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LA
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER'S RO

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER'S ROOT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNF
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUN
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRA
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR IN
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDU
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRI
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELI
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMP
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOME
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR E
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR EARLY EVEN

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR EARLY EVENING
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOM
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACK
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUM
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP D
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP DATES

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP DATES
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU LIKE ME
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU LIKE ME TO PRO
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU LIKE ME TO PROVIDE THE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU LIKE ME TO PROVIDE THE LINK
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : WOULD YOU LIKE ME TO PROVIDE THE LINK FOR THAT

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : WOULD YOU LIKE ME TO PROVIDE THE LINK FOR THAT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOL
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRA
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACK
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXP
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITION
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACK
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING US
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING NUM

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING NUMBER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY WEL
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY WELCOME
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY WELCOME HAVE
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY WELCOME HAVE A WONDER
PARTIAL [en] ttfb=4173.88ms ttft=4173.88ms conf=None : YOU ARE VERY WELCOME HAVE A WONDERFUL

UTTERANCE_FINAL [en] ttfb=495.64ms ttft=495.64ms lid_conf=None lid_label=None : YOU ARE VERY WELCOME HAVE A WONDERFUL DAY

FINAL [en] ttfb=495.64ms ttft=495.64ms elapsed=81863.59ms conf=None : THANK YOU FOR CALLING EVEREST EXPEDITIONS DELIVERY SUPPORT THIS IS SARAH HOW CAN I HELP YOU TO DAY I UNDERSTAND CAN I GET YOUR TRACKING NUMBER WHERE THE NAME ON THE ORDERS I CAN LOOK INTO IT FOR YOU THANKS LET ME PULL THAT INFORMATION UP O K I SEE YOUR PACKAGE AS MARKED AS OUT FOR DELIVERY TO DAY SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER'S ROOT UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR EARLY EVENING YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP DATES WOULD YOU LIKE ME TO PROVIDE THE LINK FOR THAT ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING NUMBER YOU ARE VERY WELCOME HAVE A WONDERFUL DAY

================================================================================
ASR BENCHMARK RESULT
================================================================================
{
  "file": "C:/Users/re_nikitav/Documents/azure_benchmarking/audio/a.wav",
  "language": "en",
  "chunk_ms": 30,
  "audio_duration_sec": 78.819,
  "client_total_elapsed_sec": 86.716,
  "streaming_elapsed_sec": 84.725,
  "real_time_factor": 1.1,
  "server_ttfb_ms": 4173.88,
  "server_ttft_ms": 4173.88,
  "server_final_elapsed_ms": 81863.59,
  "asr_confidence": null,
  "last_lid_confidence": null,
  "avg_lid_confidence": null,
  "last_lid_label": null,
  "partial_count": 145,
  "utterance_count": 9,
  "language_switch_count": 0,
  "final_text": "THANK YOU FOR CALLING EVEREST EXPEDITIONS DELIVERY SUPPORT THIS IS SARAH HOW CAN I HELP YOU TO DAY I UNDERSTAND CAN I GET YOUR TRACKING NUMBER WHERE THE NAME ON THE ORDERS I CAN LOOK INTO IT FOR YOU THANKS LET ME PULL THAT INFORMATION UP O K I SEE YOUR PACKAGE AS MARKED AS OUT FOR DELIVERY TO DAY SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER'S ROOT UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR EARLY EVENING YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP DATES WOULD YOU LIKE ME TO PROVIDE THE LINK FOR THAT ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING NUMBER YOU ARE VERY WELCOME HAVE A WONDERFUL DAY",
  "reference": null,
  "hypothesis": "THANK YOU FOR CALLING EVEREST EXPEDITIONS DELIVERY SUPPORT THIS IS SARAH HOW CAN I HELP YOU TO DAY I UNDERSTAND CAN I GET YOUR TRACKING NUMBER WHERE THE NAME ON THE ORDERS I CAN LOOK INTO IT FOR YOU THANKS LET ME PULL THAT INFORMATION UP O K I SEE YOUR PACKAGE AS MARKED AS OUT FOR DELIVERY TO DAY SOMETIMES DELIVERIES CAN RUN A BIT LAID DEPENDING ON YOUR LOCATION AND THE DRIVER'S ROOT UNFORTUNATELY WE DON'T HAVE REAL TIME TRACKING UP DATES FOR INDIVIDUAL DRIVERS HOWEVER MOST DELIVERIES ARE COMPLETED BY SIX P M SO IT'S LIKELY YOU'LL RECEIVE IT SOMETIME THIS AFTERNOON OR EARLY EVENING YOU'RE WELCOME IF YOU DON'T RECEIVE IT BY SIX P M YOU CAN ALWAYS CHECK THE TRACKING NUMBER ON LINE FOR ANY UP DATES WOULD YOU LIKE ME TO PROVIDE THE LINK FOR THAT ABSOLUTELY YOU CAN TRAP YOUR PACKAGE AT W DOT EVEREST EXPEDITIONS DOT CALM SLASH TRACKING USING YOUR TRACKING NUMBER YOU ARE VERY WELCOME HAVE A WONDERFUL DAY",
  "reference_normalized": null,
  "hypothesis_normalized": "thank you for calling everest expeditions delivery support this is sarah how can i help you to day i understand can i get your tracking number where the name on the orders i can look into it for you thanks let me pull that information up o k i see your package as marked as out for delivery to day sometimes deliveries can run a bit laid depending on your location and the drivers root unfortunately we dont have real time tracking up dates for individual drivers however most deliveries are completed by six p m so its likely youll receive it sometime this afternoon or early evening youre welcome if you dont receive it by six p m you can always check the tracking number on line for any up dates would you like me to provide the link for that absolutely you can trap your package at w dot everest expeditions dot calm slash tracking using your tracking number you are very welcome have a wonderful day",
  "wer": null,
  "wer_percent": null,
  "cer": null,
  "cer_percent": null,
  "hits": null,
  "substitutions": null,
  "deletions": null,
  "insertions": null,
  "reference_word_count": null,
  "hypothesis_word_count": 169,
  "wer_error": "No reference transcript provided"
